# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

group :development do
  gem "capistrano", "~> 3.10", require: false
  gem 'rbnacl', '< 5.0', :require => false
  gem 'rbnacl-libsodium', :require => false
  gem 'bcrypt_pbkdf', '< 2.0', :require => false
  gem 'ed25519', '< 1.3', :require => false
end
